### ISSUE TITLE
not wrking

### ISSUE THREAD

**Issue by agreements** [Wardormeur/wpphpbbunicorn#1]
at all

**Comment by Wardormeur** [comment]
Can you tell me a bit more? Same error than previous issue in the other repo?

**Comment by agreements** [comment]
Yes, precisely. Can't activate the plugin at all.

**Comment by Wardormeur** [comment]
The problem resided into the git submodule : they arent pushed, so you normally need to pull them manually. I just removed the submodule configuration to make easier for ppl to use, update and try again :)

**Comment by agreements** [comment]
now i get.

Warning: require(/var/www/wp/wp-content/plugins/wpphpbbunicorn-master/vendor/nikic/php-parser/lib/bootstrap.php): failed to open stream: No such file or directory in /var/www/wp/wp-content/plugins/wpphpbbunicorn-master/vendor/composer/autoload_real.php on line 54

**Comment by Wardormeur** [comment]
I added the missing library, same scenario than previous, it's a submodule that dont get commited.

**Comment by agreements** [comment]
Ok that activated the plugin. However now i just get a white page in wordpress even in admin area.

**Comment by Wardormeur** [comment]
Ok, i know this one ;) I still need to refine the process to configure it : actually, it' s the phpbb path that is either not set or wrong. I'll update it asap to handle a "more user friendly" way to fix it.
Thanks for your patience :+1:

**Comment by agreements** [comment]
Pretty sure i configured the phpbb path correctly :) But sure, let me know how it goes.

**Comment by Wardormeur** [comment]
All right, visibly some folks are trying it out ahah. I just fixed the white screen by adding some checks to ensure that the path fits our neeeds. The descirption is however wrong, i admit : it's not a full path but a relative one.
So, i'll take pretty much the same explaination than done on the other bug report : 

Consider phpbb and wp having their folder at the same level (/wordpress & /phpbb). Path must be relative, but to the root folder of wordpress, rendering a ../phpbb/ in my scenario. The reason behind it is that Phpbb use symfony container through a naming using the phpbb_root_path, which doesnt interpret the ":" of a Windows disk, rendering the plugin unusable for Windows folks. I may ask for a fix on their side.

**Comment by agreements** [comment]
So if my path to phpbb is and wordpress is:
/var/www/forum
/var/www/wp 
i do what in the settings file?

**Comment by Wardormeur** [comment]
In Wordpress : 
../forum
In Phpbb : 
../../phpbb

**Comment by agreements** [comment]
Just got another white page :)

**Comment by Wardormeur** [comment]
It's not supposed to white screen since last version, did you update? Else, try to add a slash at the end of the path, it "may" be that (as ../forum/ )
and *edit of my last post : 
in PhpBB : 
../../wp

**Comment by agreements** [comment]
Exactly what i did. Which caused the whitescreen.
i can send you info on the vps if you want to look at it, or have the time.

**Comment by Wardormeur** [comment]
or send me the end apache error log if you can

**Comment by Wardormeur** [comment]
Updated, you can give it a new try if you want :)

**Comment by Wardormeur** [comment]
No update, I'm closing this issue
