### ISSUE TITLE
Path problem?

### ISSUE THREAD

**Issue by knockbeats** [Wardormeur/wpphpbbunicorn#2]
Hello, moving my comments from the other page to here for this plugin as to not confuse things with cross-plugin questions :) 

It now accepts a path and doesnt go white.  However no matter what I've tried to set, it always tells me: " The path to phpbb directory is not set yet ".

my wp install path is: home/name/public_html/urlName/
my wp plugin path is: home/name/public_html/urlName/wp-content/plugins/wpphpbbunicorn/
my phpbb install path is: home/name/public_html/urlName/forums

Still unsure how to use this as it currently is, any help would be appreciated.

side questions: 

  1) Is it possible to only use this plugin, or is it required to use this plugin in conjunction with your phpbb extension?  

  2) Will this plugin allow my users to login at my WP site, and go to the my PHPBB forum without logging in again?  

  3) Does it allow comments to be taken from a wordpress post and be put as comments on the PHPBB post?  

  4) If 2 & 3 are possible, will the comments be attributed to the proper account on both wp and phpbb?  

Sorry if these are "dumb" questions, I am just learning and really trying to understand everything thats going on here.

**Comment by Wardormeur** [comment]
Yeah, the display is wrong, thanks for noticing ;)
To ensure it works, you can go into the widget part of your customisation theme and add some widgets.
Q/A : 
1) Actually, it doesnt do much without the phpbb part (not even sure it does something aha)
2) Yes
3) It can be considered, but it's not done atm
4) yes when implemented, but I'm pretty sure i wont do it in the other way (from phpbb to Wordpress) as the formatting (from phpbb) is more complicated.

**Comment by Wardormeur** [comment]
Please, update as i made some changes :)

**Comment by Wardormeur** [comment]
No update, I'm closing this issue
