### ISSUE TITLE
Wp can't activate plugin

### ISSUE THREAD

**Issue by RARgames** [Wardormeur/wpphpbbunicorn#3]
Hey
I copied all the wpphpbbunicorn files to my plugin directory(in new directory) and your plugin is showing in my wp plugin manager.
When I try to activate it the error apears: critical error: "Parse error: syntax error, unexpected '[' in /wp-content/plugins/wpphpbbunicorn/wpphpbbunicorn.php on line 86"

**Comment by RARgames** [comment]
Wp verison: 4.2.3–pl_PL
phpbb: 3.1.5-pl
I'm new to phpbb. :D Can you tell me how to install phpbbwpunicorn extension?

**Comment by RARgames** [comment]
still not working (using new wpphpbbunicorn.php)

**Comment by Wardormeur** [comment]
I'm actually at work, won't be able to look after it before tonight in best case scenario
It may be a problem with latest merge i've done

**Comment by Wardormeur** [comment]
Hey, just tested with a fresh WP install, no problem at all. Even tried in PL without result. Could you give it a try on a fresh install too? I see no reasons for it to work better but i see no reasons for it to fail either.
What is the version of PHP you're running on ?

**Comment by RARgames** [comment]
I updated php on web server to 5.4.x and now plugin works perfectly.
Ty for you help

Can u tell me how to install phpbbwpunicorn extension?

**Comment by Wardormeur** [comment]
You need to downaload the zip file, add it to your phpbb folder in ext/ in a way it should arrive with the specified path : "<phpbbfolder>/ext/wardormeur/phpbbwpunicorn"
Then it's the normal process, going to the administration panel, adctivating & stuff..

**Comment by RARgames** [comment]
Thanks again for your help.
