### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by RARgames** [Wardormeur/wpphpbbunicorn#7]
How to turn off debug mode in phpbb and get rid of this warning in wp?
It seems to be turned off in phpbb config and I tried disabling it in php.ini file

[phpBB Debug] PHP Warning: in file /wp-includes/option.php on line 772: Cannot modify header information - headers already sent by (output started at /wp-includes/functions.php:1378
[phpBB Debug] PHP Warning: in file /wp-includes/option.php on line 773: Cannot modify header information - headers already sent by (output started at /wp-includes/functions.php:1378

**Comment by Wardormeur** [comment]
It's inside your phpbb config.php

**Comment by RARgames** [comment]
So here is my config: www.pastebin.com/7DPs3RpT
What I have to do to disable debug mode?
I tried uncommenting it and putting false in 'DEBUG' and 'DEBUG_CONTAINER' but still I hae the same warnings

**Comment by Wardormeur** [comment]
Try setting it to false instead of disabling

**Comment by RARgames** [comment]
It's ok now; didn't delete cache
